"""Frozen pre-migration snapshot of SPECIES_CONFIG (with scientific_name).
Golden reference: the plugin-loaded registry must deep-equal this.
Regenerate only if a species value INTENTIONALLY changes."""

SNAPSHOT = {
    "Loxodonta africana": {
        "scientific_name": "Loxodonta africana",
        "common_name": "African Elephant",
        "water_threshold_m": 300000,
        "accessible_water_types": {"floodplain", "lake", "pan", "permanent_water", "river", "saline_lake", "surface_water", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "pan": 0.4, "wetland": 0.7, "floodplain": 0.7, "surface_water": 0.6, "saline_lake": 0.4, "permanent_water": 0.8},
        "daily_range_m": 50000,
        "water_dependency": "high",
        "icon_static_path": "app/static/Creative-Tail-Animal-elephant.svg.png",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f418.png",
        "road_sensitivity": 0.3,
        "road_threshold_m": 5000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.5,
        "settlement_threshold_m": 10000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_loxodonta_africana.gpkg",
        "emoji": "🐘",
    },
    "Equus quagga": {
        "scientific_name": "Equus quagga",
        "common_name": "Plains Zebra",
        "water_threshold_m": 150000,
        "accessible_water_types": {"floodplain", "lake", "pan", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "pan": 0.5, "wetland": 0.7, "floodplain": 0.8, "surface_water": 0.6, "permanent_water": 0.9},
        "daily_range_m": 30000,
        "water_dependency": "high",
        "icon_static_path": "app/static/Creative-Tail-Animal-zebra.svg.png",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f993.png",
        "road_sensitivity": 0.5,
        "road_threshold_m": 8000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.5,
        "settlement_threshold_m": 8000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_equus_quagga.gpkg",
        "emoji": "🦓",
    },
    "Giraffa camelopardalis": {
        "scientific_name": "Giraffa camelopardalis",
        "common_name": "Giraffe",
        "water_threshold_m": 80000,
        "accessible_water_types": {"floodplain", "lake", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "wetland": 0.6, "floodplain": 0.7, "surface_water": 0.6, "permanent_water": 0.9},
        "daily_range_m": 15000,
        "water_dependency": "moderate",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f992.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-giraffe.svg.png",
        "road_sensitivity": 0.3,
        "road_threshold_m": 5000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.4,
        "settlement_threshold_m": 8000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_giraffa_camelopardalis.gpkg",
        "emoji": "🦒",
    },
    "Panthera leo": {
        "scientific_name": "Panthera leo",
        "common_name": "Lion",
        "water_threshold_m": 200000,
        "accessible_water_types": {"floodplain", "lake", "pan", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "pan": 0.5, "wetland": 0.7, "floodplain": 0.8, "surface_water": 0.6, "permanent_water": 0.9},
        "daily_range_m": 30000,
        "water_dependency": "moderate",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f981.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-lion.svg.png",
        "road_sensitivity": 0.4,
        "road_threshold_m": 8000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.7,
        "settlement_threshold_m": 12000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_panthera_leo.gpkg",
        "emoji": "🦁",
    },
    "Acinonyx jubatus": {
        "scientific_name": "Acinonyx jubatus",
        "common_name": "Cheetah",
        "water_threshold_m": 250000,
        "accessible_water_types": {"floodplain", "lake", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "wetland": 0.5, "floodplain": 0.6, "surface_water": 0.5, "permanent_water": 0.9},
        "daily_range_m": 50000,
        "water_dependency": "low",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f406.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-cheetah.svg.png",
        "road_sensitivity": 0.6,
        "road_threshold_m": 10000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.6,
        "settlement_threshold_m": 12000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_acinonyx_jubatus.gpkg",
        "emoji": "🐆",
    },
    "Crocodylus niloticus": {
        "scientific_name": "Crocodylus niloticus",
        "common_name": "Nile Crocodile",
        "water_threshold_m": 10000,
        "accessible_water_types": {"floodplain", "lake", "permanent_water", "river", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "wetland": 0.9, "floodplain": 0.7, "permanent_water": 1.0},
        "daily_range_m": 5000,
        "water_dependency": "high",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f40a.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-crocodile.svg.png",
        "road_sensitivity": 0.3,
        "road_threshold_m": 2000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.3,
        "settlement_threshold_m": 3000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_crocodylus_niloticus.gpkg",
        "emoji": "🐊",
    },
    "Phoenicopterus roseus": {
        "scientific_name": "Phoenicopterus roseus",
        "common_name": "Greater Flamingo",
        "water_threshold_m": 50000,
        "accessible_water_types": {"lake", "permanent_water", "river", "saline_lake"},
        "water_type_weights": {"saline_lake": 1.0, "lake": 0.6, "river": 0.4, "permanent_water": 0.5},
        "daily_range_m": 30000,
        "water_dependency": "high",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f9a9.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-flamingo.svg.png",
        "road_sensitivity": 0.0,
        "road_threshold_m": 1000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.0,
        "settlement_threshold_m": 1000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_phoenicopterus_roseus.gpkg",
        "emoji": "🦩",
    },
    "Hyperolius marmoratus": {
        "scientific_name": "Hyperolius marmoratus",
        "common_name": "Painted Reed Frog",
        "water_threshold_m": 2000,
        "accessible_water_types": {"floodplain", "lake", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"wetland": 1.0, "floodplain": 0.9, "river": 0.6, "lake": 0.5, "surface_water": 0.8, "permanent_water": 0.7},
        "daily_range_m": 2000,
        "water_dependency": "high",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f438.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-frog.svg.png",
        "road_sensitivity": 1.0,
        "road_threshold_m": 2000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.1, "path": 0.0},
        "settlement_sensitivity": 0.6,
        "settlement_threshold_m": 3000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_hyperolius_marmoratus.gpkg",
        "emoji": "🐸",
    },
    "Xenopus laevis": {
        "scientific_name": "Xenopus laevis",
        "common_name": "African Clawed Frog",
        "water_threshold_m": 5000,
        "accessible_water_types": {"lake", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"lake": 1.0, "river": 0.5, "wetland": 0.8, "surface_water": 0.7, "permanent_water": 1.0},
        "daily_range_m": 5000,
        "water_dependency": "high",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f438.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-frog.svg.png",
        "road_sensitivity": 0.9,
        "road_threshold_m": 3000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.1, "path": 0.0},
        "settlement_sensitivity": 0.35,
        "settlement_threshold_m": 3000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_xenopus_laevis.gpkg",
        "emoji": "🐸",
    },
    "Hippopotamus amphibius": {
        "scientific_name": "Hippopotamus amphibius",
        "common_name": "Hippopotamus",
        "water_threshold_m": 15000,
        "accessible_water_types": {"floodplain", "lake", "permanent_water", "river", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "wetland": 0.8, "floodplain": 0.9, "permanent_water": 1.0},
        "daily_range_m": 3000,
        "water_dependency": "high",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f99b.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-hippo.svg.png",
        "road_sensitivity": 0.5,
        "road_threshold_m": 5000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.5,
        "settlement_threshold_m": 6000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_hippopotamus_amphibius.gpkg",
        "emoji": "🦛",
    },
    "Syncerus caffer": {
        "scientific_name": "Syncerus caffer",
        "common_name": "Cape Buffalo",
        "water_threshold_m": 100000,
        "accessible_water_types": {"floodplain", "lake", "pan", "permanent_water", "river", "surface_water", "wetland"},
        "water_type_weights": {"river": 1.0, "lake": 1.0, "pan": 0.5, "wetland": 0.7, "floodplain": 0.9, "surface_water": 0.6, "permanent_water": 0.9},
        "daily_range_m": 20000,
        "water_dependency": "high",
        "icon_url": "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f403.png",
        "icon_static_path": "app/static/Creative-Tail-Animal-buffalo.svg.png",
        "road_sensitivity": 0.4,
        "road_threshold_m": 6000,
        "road_class_weights": {"motorway": 1.0, "trunk": 0.9, "primary": 0.7, "secondary": 0.5, "tertiary": 0.3, "track": 0.15, "path": 0.05},
        "settlement_sensitivity": 0.5,
        "settlement_threshold_m": 8000,
        "settlement_class_weights": {"city": 1.0, "town": 0.7, "village": 0.4, "hamlet": 0.2},
        "gbif_cache_file": "gbif_syncerus_caffer.gpkg",
        "emoji": "🐃",
    },
}
